insert into participants (id, age, gender, mother_tongue, height_cm) values (1, 'cjirsa0@google.nl', 'Female', 'Māori', 373);
insert into participants (id, age, gender, mother_tongue, height_cm) values (2, 'hblampey1@miibeian.gov.cn', 'Female', 'Latvian', 544);
insert into participants (id, age, gender, mother_tongue, height_cm) values (3, 'bmardy2@mit.edu', 'Male', 'Assamese', 795);
insert into participants (id, age, gender, mother_tongue, height_cm) values (4, 'rvalentin3@weather.com', 'Female', 'Marathi', 130);
insert into participants (id, age, gender, mother_tongue, height_cm) values (5, 'fsimnel4@sphinn.com', 'Female', 'Lithuanian', 163);
insert into participants (id, age, gender, mother_tongue, height_cm) values (6, 'gcodling5@economist.com', 'Female', 'Azeri', 128);
insert into participants (id, age, gender, mother_tongue, height_cm) values (7, 'cakker6@samsung.com', 'Female', 'Guaraní', 346);
insert into participants (id, age, gender, mother_tongue, height_cm) values (8, 'charrisson7@1688.com', 'Male', 'Czech', 481);
insert into participants (id, age, gender, mother_tongue, height_cm) values (9, 'rfilinkov8@japanpost.jp', 'Female', 'Zulu', 971);
insert into participants (id, age, gender, mother_tongue, height_cm) values (10, 'lakeherst9@rakuten.co.jp', 'Female', 'West Frisian', 923);
insert into participants (id, age, gender, mother_tongue, height_cm) values (11, 'bwaddamsa@cnbc.com', 'Male', 'Tajik', 290);
insert into participants (id, age, gender, mother_tongue, height_cm) values (12, 'mmcmarquisb@sogou.com', 'Female', 'Chinese', 201);
insert into participants (id, age, gender, mother_tongue, height_cm) values (13, 'jklimptc@ft.com', 'Male', 'Kazakh', 554);
insert into participants (id, age, gender, mother_tongue, height_cm) values (14, 'wpegdend@netscape.com', 'Male', 'Haitian Creole', 892);
insert into participants (id, age, gender, mother_tongue, height_cm) values (15, 'jfoarde@zdnet.com', 'Male', 'Armenian', 912);
insert into participants (id, age, gender, mother_tongue, height_cm) values (16, 'yborrowf@google.ru', 'Female', 'Bislama', 51);
insert into participants (id, age, gender, mother_tongue, height_cm) values (17, 'aoliphardg@salon.com', 'Female', 'Lithuanian', 327);
insert into participants (id, age, gender, mother_tongue, height_cm) values (18, 'jkeeh@wordpress.com', 'Female', 'Hindi', 719);
insert into participants (id, age, gender, mother_tongue, height_cm) values (19, 'aenglandi@harvard.edu', 'Female', 'Maltese', 311);
insert into participants (id, age, gender, mother_tongue, height_cm) values (20, 'lklementzj@amazon.de', 'Male', 'Kashmiri', 69);
